- core/Cargo.toml
- core/src/default_serialisers.rs
- core/src/dispatch/mod.rs
- core/src/serialisation.rs
This single-commit PR integrates with a forked `tokio` repository which uses `bytes` v0.4.8 across all sub-crates and uses the same version for the kompics project.
> bump down  version to v0.4.8 from crates.io

- core/src/actors.rs
- core/src/dispatch/lookup.rs
- core/src/dispatch/mod.rs
- core/src/messaging/mod.rs
- core/src/runtime.rs
- core/src/utils.rs
Registration envelopes now also carry an optional `Promise` which the dispatcher fulfills upon actor registration. If the given `PathResolvable` (whether a unique, aliased, or full actor path) already exists in the actor lookup table, a warning is logged and the `Promise` yields a `RegistrationError::DuplicateEntry`.
*NOTE:* The current supported registration alias is currently only required to be `Into<String>`, not a full `Vec<String>` path like the lookup table supports.
> Futures-oriented, named actor registration

- core/src/actors.rs
- core/src/component.rs
- core/src/dispatch/lookup.rs
- core/src/dispatch/lookup/gc.rs
- core/src/dispatch/lookup/mod.rs
- core/src/dispatch/mod.rs
- core/src/lib.rs
- core/src/messaging/framing.rs
- core/src/messaging/mod.rs
- core/src/runtime.rs
- core/src/serialisation.rs
- core/src/timer/thread_timer.rs
Supports latest discussions on actor "deregistration" and cleanup.
Deregistration events have been removed: they are unnecessary because the lifecycle management already deallocates the components behind them. 
Instead, an interval-based `ActorRef` "reaper" is started upon first actor registration. This reaper is configurable in its update strategy in terms of:
* initial interval time
* maximum and minimum intervals (in milliseconds)
* separate amounts for increasing and decreasing the current interval
* feedback algorithm (currently Additive Increase/Multiplicative Decrease [AIMD] and MIMD are supported)
Defaults for these values can be found in the submodule `[core] dispatch::lookup::gc::defaults`.
Only manual tests have been done for the new functionality due to the difficulty of …
> ActorRef cleanup in dispatcher

- core/src/dispatch/mod.rs
- core/src/lib.rs
- macros/component-definition-derive/src/lib.rs
* 1d997b3  ensures the use of `std::sync::Arc` is self-contained in the component definition macro
* fdb1513 _explicitly_ exposes stuff needed to use Kompics, driven by the comments in issue #18 
@Bathtor Please look over the imports in the prelude to verify that they're all required.
> Prelude submodule & macro import fix

- core/src/lib.rs
Although i'm not certain that everything in the dispatch module should be accessible, I had to do this in order to access NetworkConfig and NetworkDispatcher for a simple actor setup.
https://github.com/Max-Meldrum/KompactExecutor/blob/master/src/main.rs
> Fix dispatch accessibility

- Cargo.lock
- experiments/dynamic-benches/Cargo.toml
- experiments/dynamic-benches/src/hashes.rs
The benches were not running the socket functions.
FxHashMap outperforms fnv on all the benches. 2.5x on UUID insert.
> Fix function call mistakes and add fxhash

- core/src/runtime.rs
As I noticed things may go very wrong if you are dumb and set threads/throughput to 0.
And for the num_cpus change:
https://github.com/rust-lang/futures-rs/pull/1835
> Add checks to config

- core/Cargo.toml
- core/src/actors/mod.rs
- core/src/component.rs
- core/src/lib.rs
- core/src/messaging/mod.rs
- core/src/runtime/system.rs
- core/src/utils.rs
This adds the ability to create components from trait objects in the form of `Box<dyn ErasedComponentDefinition<Message=M>>`. It can be useful if you want to have some runtime logic deciding what component to create.
Most of the actual implementation is in `utils::erased`. The main thing is the `ErasedComponentDefinition` trait, which is only useful if `unsized_locals` nightly feature is turned on.
The `ErasedComponent` trait could actually be extracted outside this module and renamed (`ComponentInterface`?), because it's just an amalgamation of a few other object safe traits that every component implements + `enqueue_control` method. We could probably remove most of the `_erased` versions of the `KompactSystem` methods if that was the case because we could use that trait for both the …
> Type-erased component definitions

- Cargo.lock
- core/Cargo.toml
- core/src/bin/pingperf.rs
- core/src/component.rs
- core/src/lib.rs
- core/src/ports.rs
- core/src/runtime/system.rs
- core/src/supervision.rs
- core/src/utils.rs
- docs/examples/src/batching.rs
- docs/examples/src/bin/bootstrapping.rs
- docs/examples/src/bin/buncher_adaptive.rs
- docs/examples/src/bin/buncher_config.rs
- docs/examples/src/bin/buncher_regular.rs
- docs/examples/src/bin/counters.rs
- docs/examples/src/bin/counters_channel_pool.rs
- docs/examples/src/bin/counters_pool.rs
- docs/examples/src/bin/leader_election.rs
- docs/examples/src/bin/serialisation.rs
- docs/examples/src/bin/workers.rs
- docs/examples/src/trusting.rs
- experiments/dynamic-benches/src/actorrefs.rs
- experiments/dynamic-benches/src/network_latency.rs
- macros/component-definition-derive/src/lib.rs
- macros/macro-test/src/main.rs
With #69 I added a way to create type-erased `Components` from type-erased `ComponentDefinition`s. You could even create actor references to them as usual and all was fine and dandy.
Well, mostly. You had no way of referring to the component's ports because you didn't know the concrete type! And there was no API to look ports up dynamically. This PR adds just that.
The `DynamicPortAccess` trait provides a low-level API for getting mutable refs to required/provided ports. The methods take a `TypeId` and return a `&mut dyn Any`. The lookup works by simply comparing the type ids. The implementation of this trait is generated automatically by the `#[derive(ComponentDefinition)]` macro. There is a more strictly-typed API implemented on top of that for `dyn DynamicComponentDefinition` trait …
> Dynamic port access

- macros/component-definition-derive/src/lib.rs
- macros/macro-test/src/main.rs
The ComponentDefinition macro was failing when there were multiple Required/Provided-ports in a component due to the two commas. Added the Pinger2 struct which triggered the issue that is now resolved.
> ComponentDefinition macro bugg-fix

- core/src/dispatch/mod.rs
- core/src/net/buffers/decode_buffer.rs
- core/src/net/buffers/encode_buffer.rs
- core/src/net/buffers/mod.rs
- core/src/net/mod.rs
- core/src/net/network_channel.rs
- core/src/net/network_thread.rs
- core/src/serialisation/ser_helpers.rs
- core/tests/dispatch_integration_tests.rs
- docs/src/distributed/networkbuffers.md
The NetworkTests have been cleaned up further and are now using automatically assigned ports. Closes #62 
The "Improved error messages" are pretty small in this PR the ChunkChaining PR improved it before and I've gone over the different panics/errors and I couldn't find much that can be improved further without doing much more complex error handling. Imo this closes #93 
- - - 
Harald noticed that the tutorial and Hocon parser was using an incorrect parameter name which is now fixed.
- - - 
The biggest functional change is done in the NetworkDispatcher/NetworkThread communication pattern: 
1. When a `Connected` channel is closed the NetworkThread keeps it in a `Closed` state preventing new channels to the same host from entering a `Connected` state. 
2. When the channel enters the …
> Resolving issues for 0.10.0

- core/src/lib.rs
Fixes #104
Should not be merged right away: this will require a nightly >= 2020-10-29 to compile.
Please refer to the issue for details.
> Update `unsized_locals` -> `unsized_fn_params`

- core/src/dispatch/lookup/mod.rs
- core/src/messaging/framing.rs
- core/src/net/buffers/chunk_lease.rs
- core/src/net/buffers/decode_buffer.rs
- core/src/net/mod.rs
- experiments/dynamic-benches/src/actor_store/sequence_store.rs
While we're on the subject of code cleanups, this makes a few `map_err` instances pop up and tames a couple panics.
Contributes to #116 
Failure to get a `PathType` in `SystemPathHeader`'s `TryFrom<u8>` no longer panics (and returns an Error instead).
Failure to wake the network thread in the network bridge's stop no longer provokes a crash (but does return an Error).
`match foo { Ok(bar) => Ok(bar), Err(baz) => Err(quux) }` is `foo.map_err(|baz| quux)`
> More clippy-adjacent suggestions

- core/src/actors/paths.rs
- core/src/dispatch/mod.rs
- core/src/dispatch/queue_manager.rs
- core/src/messaging/dispatch.rs
- core/src/messaging/mod.rs
- core/src/net/buffers/decode_buffer.rs
- core/src/net/frames.rs
- core/src/net/mod.rs
- core/src/net/network_thread.rs
- core/src/serialisation/ser_helpers.rs
- core/tests/dispatch_integration_tests.rs
- [✅] You ran `rustfmt` on the code base before submitting (on latest nightly with rustfmt support)
- [✅] You reference which issue is being closed in the PR text (if applicable)
Closes #120 as I've changed the timers which should make the test run smoother. I'm afraid these Network fringe-case tests won't be waterproof until we have proper simulation in place which is quite a big project.
Closes #95 
Noticed that message forwarding hadn't been updated to use chaining to avoid reserialization, which has now been fixed. Tried to simplify the code a bit but wasn't able to make stuff as neat as I hoped...
> Make Lazy Serialisation happen in the Network Thread

- core/src/messaging/framing.rs
Fixes #122.
n/a
Converts the failures in the error case of their enclosing `Result`
(more specifically InvalidData w/ a custom message).
> Removes panics in SystemPath's TryFrom<u8>

- .github/workflows/ci.yml
- .github/workflows/codecov.yml
- codecoverage-local.sh
- core/src/dispatch/mod.rs
- core/tests/dispatch_integration_tests.rs
Helps with #89, but doesn't really fix it. Should improve our ability to spot actual coverage deficits, however.
None; no code was touched.
- Use the new source-based coverage mechanism, which allows us to run tests with panics, i.e. everything in the "ignored" set.
- Separate out the workflow for code coverage. It takes a long time to run and is mostly unnecessary for iteration on PRs.
- Code coverage will now only be run for pushes to master or when requesting a review on a PR (since changes to coverage may be information a reviewer might want to know about).
> Use source-based code coverage

- .github/workflows/ci.yml
The CI makes a lot of very similar builds, this uses the cache action
to avoid having to re-load dependencies every time:
https://github.com/actions/cache
> Use caching to share cargo dependencies between builds

- core/src/component/context.rs
- core/src/lib.rs
Rust ppl decided not to stabilise this: https://github.com/rust-lang/rust/issues/62633#issuecomment-777009499
- Remove nightly-only usages of `Option::expect_none` in favour of the more verbose `assert!(Option::is_none())`
> Remove usages of expect_none

- .github/workflows/ci.yml
- Cargo.lock
- core/src/actors/mod.rs
- core/src/actors/paths.rs
- core/src/default_components.rs
- core/src/dispatch/lookup/gc.rs
- core/src/dispatch/mod.rs
- core/src/lib.rs
- core/src/net/mod.rs
- core/src/net/network_channel.rs
- core/src/net/network_thread.rs
- core/src/runtime/system.rs
- core/tests/dispatch_integration_tests.rs
- docs/examples/src/bin/dns_resolver.rs
- docs/examples/src/bin/serialisation.rs
- docs/src/distributed/networkstatusport.md
- docs/src/distributed/serialisation.md
* Added a NetworkStatusPort which components may connect to to receive NetworkStatusUpdate indications or send NetworkStatusRequests to the Dispatcher.
* Protocol to distinguish between gracefully closed channels and lost connections implemented.
* Docs page added for the NetworkStatusPort.
* Added public method `SystemPath::socket_address() -> SocketAddr` 
* Added public method `System::kill_system()` which kills a system without doing graceful shutdown of network channels.
* Components can send two requests on the NetworkStatusPort: `ConnectSystem(SystemPath)` which allows systems to initiate connections without sending messages to actors on the system, for set-up phases and network-overlay-management. And `DisconnectSystem(SystemPath)` which will initiate graceful disconnection between …
> NetworkStatusPort

- Cargo.lock
- core/Cargo.toml
- core/src/lib.rs
- core/src/messaging/deser_macro.rs
- core/src/net/buffers/mod.rs
- core/src/net/mod.rs
- core/src/routing/mod.rs
- core/src/utils/checked_casts.rs
- core/src/utils/mod.rs
- core/tests/compile-fail/match_deser_tests.rs
- core/tests/compile-fail/match_deser_tests.stderr
- core/tests/macro_compile_tests.rs
- docs/examples/src/bin/bootstrapping.rs
- docs/examples/src/bin/load_balancer.rs
- docs/examples/src/bin/serialisation.rs
- docs/src/distributed/basiccommunication.md
- docs/src/distributed/namedservices.md
- docs/src/distributed/networkbuffers.md
Fixes #37.
- New syntax for the `match_deser` macro
For some `msg: NetMessage`.
Old:
```rust
match_deser! { msg; {
res: MsgA [MsgA] => EitherAOrB::A(res),
res: MsgB [BSer] => EitherAOrB::B(res),
!Err(_e) => panic!("test panic please ignore"),
_ => unimplemented!("Should be either MsgA or MsgB!"),
}}
```
Becomes New:
```rust
match_deser! {
msg {
msg(res): MsgA => EitherAOrB::A(res),
msg(res): MsgB [using BSer] => EitherAOrB::B(res),
err(_e) => panic!("test panic please ignore"),
default(_) => unimplemented!("Should be either MsgA or MsgB!"),
}
}
```
- Reading buffer sizes from HOCON now allows unit specifications, e.g. "256KB".
> New match_deser macro implementation

- core/src/default_components.rs
- core/src/dispatch/mod.rs
- core/src/lib.rs
- core/src/net/mod.rs
- core/src/net/network_thread.rs
- core/src/supervision.rs
- core/src/utils/mod.rs
Just a comment from #147 
None
- Added the new `Completable` trait to `KPromise`, allowing promises to be fulfilled using the default value of the underlying type by calling `promise.complete()`.
> Complete promises without providing a value

- Cargo.lock
- core/Cargo.toml
- core/src/net/buffers/mod.rs
- core/src/net/mod.rs
- core/src/net/network_channel.rs
- core/src/net/network_thread.rs
- core/tests/dispatch_integration_tests.rs
I believe this may resolve #130 but I'll keep the issue open for a while longer and see how the testing behaves while I work on the other issues.
Fixed a minor bug when closing a connection (one line removed in the NetworkThread).
I replaced the timers in the dispatch_integration_tests with KPromises in all the places where this could be done easily. There's still a bunch of timers left which I think is unavoidable for the things they test.
> Refactored and changed integration tests to get rid of flaky test cases

- Cargo.lock
- core/Cargo.toml
- core/src/component/mod.rs
- core/src/dispatch/mod.rs
- core/src/lib.rs
- core/src/messaging/mod.rs
- core/src/net/mod.rs
- core/src/net/network_channel.rs
- core/src/net/network_thread.rs
- core/src/routing/groups.rs
- core/src/routing/mod.rs
- core/tests/dispatch_integration_tests.rs
Add Status message for Connection Limit Exceeded.
Closes #83 
Added two configurable Connection Limits, `Hard Connection Limit` and `Soft Connection Limit` which limits the amount concurrent active connections a system may have. 
`Soft Connection Limit`limits the number of concurrent Active Connections a system may have, while the hard limit limits the total number of connections (i.e. in process of closing or handshake for new connections).
When the Soft Limit is exceeded by a new connection entering the connected state, the least recently used active connection will be closed gracefully. 
When the Hard Limit is reached by new incoming or outgoing requests, the requests will be denied immediately.
The new integration …
> Connection Limit added.

- core/src/dispatch/mod.rs
- core/src/dispatch/queue_manager.rs
- core/src/net/mod.rs
- core/src/net/network_channel.rs
- core/src/net/network_thread.rs
- core/tests/dispatch_integration_tests.rs
Made NetworkDispatcher catch panics in the NetworkThread and launch a new NetworkThread.
Added two simple integration tests which induces a panic in the NetworkThread and asserts that it successfully re-establishes the connection. The tests set up a pinger and a ponger system and differs by which system they induce a panic in.
Closes #144 
**Change in expected behaviour:**   
A panic in the NetworkThread may be caused by an incorrect serialiser, which would previously just cause the system to crash entirely. If the `NetworkThread` panics the entire local system will not panic, but instead it will re-launch the `NetworkThread`.  
**Message loss scenarios:**   
Outgoing messages sent after a local NetworkThread panic, but …
> Make KompactSystem recover from Panics in the NetworkThread

- core/src/net/mod.rs
- core/tests/dispatch_integration_tests.rs
Just tiny changes in the net_test_helpers actors and the dispatch_integration_tests.
> Fixing a flaky test

- docs/src/distributed/networkstatusport.md
Just changes to the Kompact Book.
> Update Docs for NetworkStatusPort to reflect the recent additions made

- .github/workflows/ci.yml
- .github/workflows/codecov.yml
- core/src/component/future_task.rs
- core/src/dispatch/mod.rs
- core/src/lib.rs
- core/src/net/buffers/decode_buffer.rs
- core/src/net/network_thread.rs
- core/src/runtime/scheduler.rs
- core/src/timer/timer_manager.rs
- core/tests/compile-fail/component_derive_tests.stderr
- core/tests/dispatch_integration_tests.rs
Fixed the Macros Test Output to match the new output. 
Bumped the CI-nightly version and attended to the latest warnings.
> Macro test output and bump CI-nightly version

- Cargo.lock
- core/src/component/future_task.rs
- ~~[ ] You reference which issue is being closed in the PR text (if applicable)~~
- Nightly was failing because dropping a `ManuallyDrop` was unsafe.
- Rust has meanwhile stabilised `Arc::increment_strong_count`, so we can just use this instead.
Ran `cargo update`.
> Fix nightly build issue

- .github/workflows/ci.yml
- Github is phasing out v2 cache action, so this PR updates it to the latest v4.
> Update Github cache actions from v2 to v4
